### ISSUE TITLE
probable wrong translation of set.mm to the mm0 format

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#10]
The beginning translation from set.mm that I got with mm0-hs fromMM 
has suspiscious SVar and App tokens that have no definition

> delimiter $ ( ) $;
>
>provable sort wff;
>
>theorem dummylink (ph ps: wff):
>  $ SVar "ph" $ >
>  $ SVar "ps" $ >
>  $ SVar "ph" $;
>
>theorem idi (ph: wff):
>  $ SVar "ph" $ >
>  $ SVar "ph" $;
>
>term wn (ph: wff): wff;
>
>term wi (ph ps: wff): wff;
>
>axiom ax_mp (ph ps: wff):
>  $ SVar "ph" $ >
>  $ App "wi" [SVar "ph",SVar "ps"] $ >
>  $ SVar "ps" $;

**Comment by digama0** [comment]
It looks like the printer was commented out and replaced by the debugging printer for testing purposes; I've restored it to the right behavior.

**Comment by Lakedaemon** [comment]
Thanks for that, it looks much better now and I can start debugging my parser/implementing coercion/improve type-checking now and implement a verifier later.
Many thanks :) (also, you are fast, I like that :)
