### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#11]
in the Pseudo-keywords part

This is not really important but this sentence confuses me, it contradicts itself, right ?
"never" should be removed, right ?

However, they are not really "keywords" because the grammar **never** permits these words to appear where an identifier can also appear. So they are lexed simply as identifiers, and it is permissible to declare a variable, sort, or theorem with one of these keywords as its name.

**Comment by digama0** [comment]
Ah, I can see why that phrasing would be confusing. What it is trying to say is that whenever a keyword is valid as the next token, i.e. after a semicolon or some modifier keywords, the "identifier" nonterminal is not valid, so there is no danger of identifiers being confused for keywords. In linguistic terminology, they are in "complementary distribution".

**Comment by Lakedaemon** [comment]
Thanks for the explanation and for the change.

Also, the new documentation has another benefit : it shows that the author of mm0 has put a great deal of thought into this particular design (and the reader can envision the benefits). 
So, it somewhat helps to explain that mm0 is really great stuff, nicely designed. 
And this is like honey to a developer looking for a library to achieve some goal.
