### ISSUE TITLE
[mm0-rs] Use of 'let...else' prevent cargo to compile

### ISSUE THREAD

**Issue by Sylvain78** [digama0/mm0#117]
I got many erros :  error[E0658]: `let...else` statements are unstable 
while compiling with `cargo build --release`

**Comment by bjorn3** [comment]
Which rust version are you using? It has been stable since rust 1.65.

**Comment by digama0** [comment]
Yes, `rustup update stable` should fix this issue. mm0-rs has an MSRV of latest stable (it's not a library so I don't see much point in not taking advantage of new rust features).
