### ISSUE TITLE
Consider replacing /docs/index.html with /mm0.md

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#18]
`mm0.md` seems to be (both in content and going by revision history) a more up to date piece of reference material than `/docs/index.html`. Specifically the grammar laid out in `/mm0.md` more closely reflects what's in `/examples`.

**Comment by digama0** [comment]
Oops, yeah I wasn't even sure what you meant by `/docs/index.html`. As the commit says, that file was just a test, to see if I get a web page (and indeed https://digama0.github.com/mm0/ works). But it needs to be hooked up to CI to not rot.
