### ISSUE TITLE
Run rustfmt on mm0-rs

### ISSUE THREAD

**Issue by brendanzab** [digama0/mm0#21]
I've been browsing the mm0-rs sources out of curiosity, and it seems to be using a non-standard formatting style. Would it be possible to run rustfmt on these sources?

**Comment by digama0** [comment]
Yes, but only if I can make rustfmt look reasonably close to the style I use. Formatting matters to me and I have heard some bad things about projects that have it on continuously, c.f. https://internals.rust-lang.org/t/forced-rustfmt-is-a-roadblock-to-contributing/11913.

**Comment by brendanzab** [comment]
I think it works best if you use it as you develop - like, you can work with it by doing things like splitting things up into multiple bindings to make things format nicer. I agree with the linked post that rustfmt should take into account human judgement more (like elm-format), but on the whole it seems like it's more of a roadblock to contributions if the code formatting of a project looks very different from the rest of the ecosystem.

**Comment by brendanzab** [comment]
But yeah, the main point was around the non-standard styling, and if you disagree with this I understand! It _would_ however make me less likely to play around with the code in the future. I'm very interested in mm0 though, it looks like a really cool project and I wish you the best for it! :) Feel free to close this if you like!

**Comment by digama0** [comment]
If parts of this code eventually go into a cargo crate or something like that, I'll probably switch to standard formatting. But for now I'm just a one man band and I have never used rustfmt in my "process" so it's more likely to cause friction than deliver any concrete benefits at this point. (The main important thing for me is the 2 space indent, for other stuff I can live with a bit of conformity.)
