### ISSUE TITLE
How easy is it to write  python API for this for Machine Learning (like what CoqGym has)?

### ISSUE THREAD

**Issue by brando90** [digama0/mm0#24]
How easy is it to write  python API for this for Machine Learning (like what CoqGym has)?

Specially because I'v been told this is **fast**. Are there benchmarks comparing it to other ITPs?

Btw, Is there a declarative version of this?

**Comment by digama0** [comment]
I think it could be possible to set up bindings to the Rust server to accomplish this. What kind of interface are you looking for? Right now the tactic infrastructure is pretty poor in terms of what operations you can do. Mainly you can apply a theorem and get back subgoals, or posit a term and store it for later use. But the server would end up doing so little work that you might be better off just doing the unification etc on the python side.

**Comment by digama0** [comment]
As for declarative version, I'm not sure what you mean. The MM1 interface allows you to write proof terms, and completed proofs look like big proof terms for the most part. You can use `have` to posit a subgoal, but it's not strictly structured in the manner of a declarative proof language.

**Comment by digama0** [comment]
As for benchmarks, that would require an unbiased point of comparison, which doesn't really exist at present. I could prove irrationality of the square root of two in peano.mm1 as that seems to be a popular target (although formalizing real numbers in PA is an interesting proposition to say the least). My guess is that approximately anything reasonable will compile end-to-end in about half a second. Individual proofs are around a millisecond of work.

**Comment by digama0** [comment]
I'm closing this in favor of #34 . More precise details on the Python setup will be needed to address this particular use-case.
