### ISSUE TITLE
malformed lisp def panics server

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#28]
mwe :

```
do {
  (def x 10)
  (print x)
  (def x)
};
```

the VScode output shows:
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/server.rs:641:17 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

The `(def x)` has to be after some earlier definition of `x` for this to trigger.

**Comment by digama0** [comment]
That's not malformed; the second expression is the same as `(def x #<undef>)` and has the effect of deleting `x` from the global context (i.e. it is like an `(undef)` command). That doesn't explain why it panics, but the ability to undefine symbols was added later so it's likely that something was relying on this being impossible.

**Comment by ammkrn** [comment]
I stand corrected.
