### ISSUE TITLE
Proof stream opcode "Hyp" pushes to heap instead of stack.

### ISSUE THREAD

**Issue by IvoWingelaar** [digama0/mm0#3]
In mm0-c, the comments near the execution of `CMD_PROOF_HYP` claims it pushes `|- e` to the main stack (as specified in the [paper](https://arxiv.org/abs/1910.10703)), but the code pushes it to the main heap instead.

**Comment by digama0** [comment]
The code's behavior is the correct one. (We don't usually have any guarantee that the hypotheses will be used, or used in the right order, so it is more convenient to have them in the heap instead so we can reference them 0 or more times.) I will update the paper.

**Comment by digama0** [comment]
The comment to `mm0-c/verifier.c` for `CMD_PROOF_HYP` was also in error; fixed in 0c556a2.
