### ISSUE TITLE
mm0-c rejects theorems with named hypotheses (minor)

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#70]
This only seems to be a small issue with the grammar in mm0.md; mm0-c rejects public theorems if the hypotheses are named, but the grammar allows fml-type-binder* in theorems.

With this theorem in a mm1 file:
```
pub theorem a1i (a b: wff) (h: $ b $): $ a -> b $ = '(ax_mp ax_1 h);
```

The following is accepted by mm0-c:
```
theorem a1i (a b: wff): $ b $ > $ a -> b $;
```

But these are rejected with the error `at a1i: too many arguments`:
```
theorem a1i (a b: wff) (h: $ b $): $ a -> b $;
theorem a1i (a b: wff) (h: $ b $ ): $ b $ > $ a -> b $;
```

**Comment by digama0** [comment]
This is a bug in mm0-c (I also found this bug somewhat recently while writing the [tutorial](https://www.youtube.com/watch?v=A7WfrW7-ifw)). As you noticed, it's easy to work around the bug by writing the mm0 file without named hypotheses, but it should support this.

**Comment by ammkrn** [comment]
Thanks. I'll leave this open as a reminder, but feel free to close it if you don't want to look at it.
