### ISSUE TITLE
Diagnostic severity is elevated for upstream errors

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#71]
[this portion of elab.rs](https://github.com/digama0/mm0/blob/aebedf4a5406201d4ee6cbbd16e09808667be513/mm0-rs/src/elab.rs#L707) handles upstream errors with the constructor `ElabError::new()`, which automatically sets the diagnostic severity to `error`.

As a result, importing a file that has any info/warn level items in it causes the downstream file to report a hard error (the position of which is displayed with `:#x` formatting which might not be ideal).

filtering `errs` and just making a new collection of ElabErrors seems like it would be the easiest solution since error reporting is an infrequent operation.

**Comment by digama0** [comment]
What's your preferred alternate behavior here? Should it report upstream errors with the same level of severity (i.e. you get an info level diagnostic on the import if there are info level errors in the file), or should it just suppress all non-error errors upstream (so you only get an error if there are errors, and if there are warnings or infos you get nothing)?

**Comment by digama0** [comment]
This doesn't fix the `:#x` formatting issue. The problem is that we don't have the context to figure out line/col positions there, and even worse, the error might be sourced from a file that doesn't even have lines and columns, for example if you `import "foo.mmb";`  the file is binary so lines and cols don't make much sense (although perhaps even pointing into the file with specificity at all is unhelpful).

**Comment by ammkrn** [comment]
> What's your preferred alternate behavior here?

I'm happy as long as things that aren't hard errors don't become hard errors; the err |-> err, warn |-> warn, info |-> nothing pattern seems fine to me. Long term, it would be cool if this kind of behavior could be specified with lints.

**Comment by digama0** [comment]
I added upstream warnings in aa06306 and a server option for disabling upstream error reporting (which I have been annoyed by in lean before, which is why the option already existed; it's disabled in command-line mode).

**Comment by ammkrn** [comment]
Much appreciated.
