### ISSUE TITLE
Need help to build mm0

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#9]
I would like to build mm0-hs on my linux box (ubuntu)
I set up haskel platform
I managed to build (or I think I did) setup.hs with 
` ghc -o ./mm0 ./Setup.hs

apparently it allows me to do
mm0 configure (except it fails because a cabal file is missing)
mm0 build (require configure)
mm0 installe (same)

I also failed to build with
`ghc -o mm0 Main.hs

[ 1 of 35] Compiling MM0.Util         ( MM0/Util.hs, MM0/Util.o )

MM0/Util.hs:34:16: error:
    • Non type-variable argument in the constraint: MonadError String m
      (Use FlexibleContexts to permit this)
    • In the type signature:
        withContext :: MonadError String m => T.Text -> m a -> m a

I would like to convert the huge set.mm file myself and also to build the mm0 tools (might need those later). Please provide guidance.

**Comment by digama0** [comment]
I use Haskell stack for building. Using ghc directly requires a ton of options on the command line, like C/C++ compilers, and stack uses the .stack.yml file to handle all that. Instructions should be in the mm0-hs/readme file.

**Comment by Lakedaemon** [comment]
thanks for the hint "Haskell stack". 
I downloaded it, managed to do stack setup...maybee I'll be able to do a mm0 frommm next

**Comment by Lakedaemon** [comment]
There weren't instructions in mm0-hs/readme
So, for your future contributors : 
1) install Haskel Stack from https://docs.haskellstack.org/en/stable/README/
2) go in the mm0/mm0-hs directory and do
stack setup
3) do
stack build
4) do stack install
5) then it tells you were it installed mm0-hs

I was able to convert set.mm to set.mm0
Many thanks for the hint, again :)

**Comment by digama0** [comment]
TODO: fix documentation

**Comment by Lakedaemon** [comment]
I pulled the latest changes and did
stack update
stack clean 
stack purge
stack build
-----> it asked me to do stack init (which it did not before)
I did stack init with this result 
Selected resolver: lts-14.25
Resolver 'lts-14.25' does not have all the packages to match your requirements.
    async-pool not found
        - mm0-hs requires -any
    dynamic-mvector not found
        - mm0-hs requires -any

Sadly, I haven't been able to get stack to build the latest version of mm0-hs.
I'll investigate a bit and hopefully find a solution

Meanwhile the fixes for mm0.mm0 and peano.mm0 made my parser able to parse them.
:)

**Comment by Lakedaemon** [comment]
this is weird
those packages aren't in the resolver (which is normal)
They look ok in the stack.yaml file
(async-pool even has a newer version on hackage).
It looks like stack build or stack init doesn't understand the stack.yaml part that says it has to go and fetch those package on hackage...
investigating further...

**Comment by Lakedaemon** [comment]
nevermind. I am stupid
I needed to do 
stack build in the mm0-hs directory and I was doing it in the mm0-master directory
(how stupid can I be ?)
